export const experiences = [
  {
    title: "Full Stack Developer",
    company: "Saciva",
    duration: "DEC 2024 - Present",
    description: `At Saciva, I work as a Full Stack Developer handling frontend, backend, and DevOps. The frontend (Next.js + DuckDB) is deployed on Vercel, and the backend (Express.js) is hosted on Hostinger with zero-downtime updates. I containerized the app with Docker, set up Nginx for scalability, and implemented monitoring using Sentry, Grafana, and Prometheus.`,
    image: "/projects/saciva.png",
  },
  {
    title: "React Native Intern",
    company: "HumanEra Intelligence",
    duration: "JUL 2025 - SEP 2025",
    description: `Developed a cross-platform mobile app using React Native and Expo. Implemented user authentication with Clerk and managed state using Zustand for a seamless user experience. Adopted a local-first approach and integrated GraphQL for efficient data handling.`,
    image: "/projects/hui.png",
  },
  {
    title: "Freelance Developer",
    company: "Self-Employed",
    duration: "AUG 2025 - Present",
    description: `As a freelance developer, I build full-stack web and mobile applications for clients across various industries. I specialize in creating scalable, production-ready solutions using modern technologies like Next.js, React Native, FastAPI, and Go.`,
    image: "/projects/frees.png",
  },
];

export const projects = [
  {
    id: 1,
    title: "OmniAI",
    description: "Chat with documents and websites through intelligent AI conversations. Get instant answers from your content.",
    fullDescription: "OmniAI is an advanced AI-powered platform that enables users to have intelligent conversations with their documents and websites. Built with cutting-edge technologies like LangChain and Pinecone for vector storage, it provides instant, contextual answers from your content. The platform features real-time processing, secure document handling, and seamless integration with various file formats.",
    tech: ["Next.js", "TypeScript", "TailwindCSS", "Go", "FastAPI", "LangChain", "Redis", "Pinecone", "Postgresql", "Docker", "gRPC", "RabbitMQ", "nginx"],
    category: "AI/ML",
    github: "https://github.com/Rana718/omniai",
    demo: null,
    image: "/projects/omniai.png",
    featured: true,
  },
  {
    id: 2,
    title: "CareerWise",
    description: "AI interview prep with mock sessions, feedback, and guidance. Built with Next.js, prisma and Gemini.",
    fullDescription: "CareerWise is a comprehensive AI-powered interview preparation platform that helps job seekers practice and improve their interview skills. It features mock interview sessions, real-time feedback, personalized guidance, and performance analytics. Built with modern technologies for a seamless user experience.",
    tech: ["Next.js", "TailwindCSS", "Prisma", "TypeScript", "Postgresql", "Framer Motion", "Gemini"],
    category: "Web App",
    github: "https://github.com/Rana718/HireLens",
    demo: "https://careerw-ise.vercel.app/",
    image: "/projects/careerwise.png",
    featured: true,
  },
  {
    id: 3,
    title: 'AI Resume Builder',
    description: 'Built AI resume builder with automated CV generation, cover letter creation, payment integration, user management, and analytics dashboard for subscription-based service.',
    longDescription: 'Full-stack AI-powered resume builder with Next.js frontend and FastAPI backend. Features include CV generation, cover letter creation, LinkedIn integration, payment processing, and admin dashboard with Docker deployment.',
    tech: ['NextJS', 'TypeScript', 'TailwindCSS', 'Framer Motion', 'Zustand', 'FastAPI', 'SQLAlchemy', 'Firebase', 'Postgresql', 'Razorpay', 'Docker', 'Redis', 'OpenAI'],
    category: 'Web App',
    github: 'https://github.com/Rana718/cvbuilder',
    // demo: 'https://peerdrop-theta.vercel.app/',
    image: '/projects/aicv.png',
    featured: true,
    status: 'completed'
  },

  {
    id: 4,
    title: "KhelRatna",
    description: "Cricket tournament management platform with live score tracking and YouTube match streaming.",
    fullDescription: "KhelRatna is a dedicated platform for hosting and managing cricket tournaments. Organizers can create and manage tournaments, update scores in real time, and provide detailed statistics. Players and teams can track their performances, while audiences can follow live scores and even watch tournament matches streamed directly through YouTube integration.",
    tech: ["Next.js", "Clerk", "Flutter", "Prisma", "TypeScript", "Framer Motion", "TailwindCSS"],
    category: "Mobile App",
    github: "https://github.com/Rana718/khelratna_user",
    demo: "https://play.google.com/store/apps/details?id=com.khelratna.app",
    image: "/projects/khelratna.png",
    featured: true,
  },
  {
    id: 5,
    title: "Flash ORM",
    description: "A powerful, database-agnostic ORM built in Go with Prisma-like functionality and multi-database support.",
    fullDescription: "Flash ORM is a high-performance database ORM that outperforms Drizzle and Prisma by 3-12x in benchmarks. It provides safe transaction-based migrations, visual database management through Flash Studio, and generates type-safe code for Go, JavaScript/TypeScript, and Python. Features include schema introspection, multi-format exports (JSON, CSV, SQLite), and support for PostgreSQL, MySQL, and SQLite databases.",
    tech: ["Go", "PostgreSQL", "MySQL", "SQLite", "SQLC", "Cobra CLI", "JavaScript", "TypeScript", "Python"],
    category: "Backend",
    github: "https://github.com/Lumos-Labs-HQ/flash",
    demo: null,
    image: "/projects/graft.png",
    featured: true,
  },
  {
    id: 6,
    title: 'Passman',
    description: 'Secure password manager with end-to-end encryption, multi-factor authentication, vault management, zero-trust mode, and recovery keys for account protection.',
    longDescription: 'A full-stack password manager with end-to-end encryption, multi-factor authentication (TOTP/Email OTP), vault management, zero-trust mode, and 40 recovery keys for secure password reset and account recovery.',
    tech: ['SvelteKit', 'TypeScript', 'TailwindCSS', 'Framer Motion', 'FastAPI', 'PostgreSQL', 'SQLAlchemy', 'Redis'],
    category: 'Web App',
    github: 'https://github.com/Rana718/passman',
    // demo: 'https://peerdrop-theta.vercel.app/',
    image: "/projects/passman.png",
    featured: true,
    status: 'completed'
  },
  {
    id: 7,
    title: "PeerDrop",
    description: "Instant, secure file sharing via peer-to-peer tech with end-to-end encryption. Built with React, Go, and WebSockets.",
    fullDescription: "PeerDrop revolutionizes file sharing with peer-to-peer technology and end-to-end encryption. No file size limits, no server storage, just direct, secure transfers between devices. Built with React frontend and Go backend using WebSockets for real-time communication.",
    tech: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "Go", "WebSocket"],
    category: "Web App",
    github: "https://github.com/Rana718/file_sharing",
    demo: "https://peerdrop-theta.vercel.app/",
    image: "/projects/peerdrop.png",
    featured: false,
  },
  {
    id: 8,
    title: "NewsApp",
    description: "A news aggregator app that fetches the latest news from various sources using NewsAPI.",
    fullDescription: "NewsApp is a modern news aggregator that pulls the latest articles from multiple sources using the NewsAPI. It features a clean, responsive design with categories for easy navigation, and allows users to search for specific topics. Built with Next.js and TailwindCSS, it provides a seamless user experience with fast loading times and smooth transitions.",
    tech: ["React Native", "expo", "TypeScript", "TailwindCSS", "NewsAPI"],
    category: "Mobile App",
    github: "https://github.com/Rana718/NewsApp",
    demo: null,
    image: "/projects/newsapp.jpg",
    featured: false,
  },
  {
    id: 9,
    title: "Snipity",
    description: "Minimal code editor for creating and sharing snippets easily. Built with Next.js, Convex, Zustand, and Framer Motion.",
    fullDescription: "Snipity is a modern, minimal code editor designed for developers to create, edit, and share code snippets effortlessly. Features syntax highlighting, real-time collaboration, snippet organization, and seamless sharing capabilities. Built with Next.js and powered by Convex for real-time data synchronization.",
    tech: ["Next.js", "Convex", "TypeScript", "Framer Motion", "Zustand"],
    category: "Web App",
    github: "https://github.com/Rana718/snipity",
    demo: "https://snipity.vercel.app/",
    image: "/projects/codeCraft.png",
    featured: false,
  },
  {
    id: 10,
    title: "URL Shortener",
    description: "Fast, in-memory URL shortener using BigCache for quick link generation. Built with React, Go, and Docker.",
    fullDescription: "A high-performance URL shortening service built with Go and React. Features in-memory caching with BigCache for lightning-fast redirects, analytics tracking, custom short URLs, and bulk URL processing. Containerized with Docker for easy deployment and scaling.",
    tech: ["React", "Vite", "TypeScript", "Go", "Fiber", "Redis", "Docker"],
    category: "Web App",
    github: "https://github.com/Luciferair/link-shortner",
    demo: "https://shortify-link-shortener.vercel.app/",
    image: "/projects/urlshort.png",
    featured: false,
  },
  {
    id: 11,
    title: "Pinglo",
    description: "Real-time chat application with modern UI and seamless messaging experience.",
    fullDescription: "Pinglo is a real-time chat application built for modern communication needs. Features include instant messaging, group chats, file sharing, emoji reactions, and user presence indicators. Built with React and Socket.IO for real-time communication.",
    tech: ["Next.js", "Socket.IO", "Framer Motion", "TailwindCSS", "TypeScript", "Express", "MongoDB"],
    category: "Web App",
    github: "https://github.com/Rana718/pinglo",
    demo: null,
    image: "/projects/pinglo.png",
    featured: false,
  },
  {
    id: 12,
    title: "AI App",
    description: "A simple AI app where user can generate images and text using Gemini.",
    fullDescription: "AI App is a simple yet powerful application that allows users to generate images and text using the Gemini AI model. It features a user-friendly interface, real-time generation capabilities, and supports various input formats for both text and image generation.",
    tech: ["React Native", "expo", "clerk", "TypeScript", "TailwindCSS", "Gemini"],
    category: "Mobile App",
    github: "https://github.com/Rana718/Image_AI_App",
    demo: null,
    image: "/projects/aiapp.jpg",
    featured: false,
  },
  {
    id: 13,
    title: "Magic Pad",
    description: "A creative drawing tool inspired by Apple's calculator sketchpad. Built for fun and interaction.",
    fullDescription: "Magic Pad is an innovative drawing application inspired by Apple's calculator sketchpad feature. It combines creativity with AI, allowing users to draw and interact with their sketches in unique ways. Features include gesture recognition, AI-powered sketch analysis, and interactive drawing tools.",
    tech: ["React", "Vite", "TypeScript", "FastAPI", "Gemini"],
    category: "Creative Tool",
    github: "https://github.com/Rana718/MagicPad",
    demo: "https://magic-pad.vercel.app/",
    image: "/projects/megic.png",
    featured: false,
  },
  {
    id: 14,
    title: "Tic Tac Toe Game",
    description: "Modern Tic Tac Toe with bot, offline, and online multiplayer using Socket.IO and Redis.",
    fullDescription: "A modern take on the classic Tic Tac Toe game featuring multiple game modes including AI bot, offline play, and real-time online multiplayer. Built with React and Socket.IO for seamless real-time gameplay, Redis for session management, and beautiful animations with Framer Motion.",
    tech: ["React", "Vite", "Framer Motion", "Socket.IO", "Express"],
    category: "Game",
    github: "https://github.com/Rana718/tic-tac-toe",
    demo: null,
    image: "/projects/tic-tac-toe.png",
    featured: false,
  },
  {
    id: 15,
    title: "Fitly",
    description: "AI-powered web app that helps users find the best jobs based on their skills and interests.",
    fullDescription: "Fitly is an AI-powered web application designed to connect users with the most suitable job opportunities. It also allows users to generate tailored CVs based on job descriptions, making the application process smarter and more efficient.",
    tech: ["Next.js", "TypeScript", "TailwindCSS", "Framer Motion", "FastAPI", "Postgresql", "Python", "Selenium", "Gemini"],
    category: "Web App",
    github: "https://github.com/Rana718/Fitly",
    demo: null,
    image: "/projects/fitly.png",
    featured: false,
  },
];

export const skills = {
  frontend: {
    title: "FRONTEND",
    tech: "TypeScript, React, Next.js, SvelteKit, Framer Motion",
    description: "Building responsive and interactive user interfaces",
  },
  backend: {
    title: "BACKEND",
    tech: "Node.js, Express, FastAPI, Flask, Go Fiber",
    description: "Scalable server-side applications and APIs",
  },
  mobile: {
    title: "MOBILE",
    tech: "React Native, Expo, Flutter, Kotlin",
    description: "Cross-platform mobile applications",
  },
  database: {
    title: "DATABASE & DEVOPS",
    tech: "PostgreSQL, MongoDB, Redis, Docker, AWS, Kafka, K8s",
    description: "Database management and cloud infrastructure",
  },
};
