"use client";

import mermaid from "mermaid";
import { useEffect, useId, useState } from "react";
import { useTheme } from "@/lib/theme-provider";

interface MermaidDiagramProps {
	chart: string;
}

export function MermaidDiagram({ chart }: MermaidDiagramProps) {
	const reactId = useId();
	const [svg, setSvg] = useState("");
	const [error, setError] = useState("");
	const { theme } = useTheme();

	useEffect(() => {
		let active = true;
		// Each render needs a unique id so Mermaid doesn't conflict with a
		// previously cached element when we re-render for a theme change.
		const id = `mermaid-${reactId.replace(/[^a-zA-Z0-9]/g, "")}-${theme}`;

		mermaid.initialize({
			startOnLoad: false,
			securityLevel: "strict",
			theme: theme === "dark" ? "dark" : "default",
			flowchart: {
				htmlLabels: true,
				useMaxWidth: true,
				wrappingWidth: 200,
				nodeSpacing: 32,
				rankSpacing: 40,
			},
			sequence: {
				useMaxWidth: true,
			},
			gantt: {
				useMaxWidth: true,
			},
		});

		// Reset svg so there's no flash of the old-theme diagram while the new
		// one is rendering.
		setSvg("");
		setError("");

		mermaid
			.render(id, chart)
			.then(({ svg: renderedSvg }) => {
				if (active) setSvg(renderedSvg);
			})
			.catch((reason: unknown) => {
				if (active) {
					setError(reason instanceof Error ? reason.message : "Invalid diagram");
				}
			});

		return () => {
			active = false;
		};
	}, [chart, reactId, theme]); // re-run whenever theme changes

	if (error) {
		return (
			<div className="my-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4 font-mono text-sm text-red-500">
				Diagram error: {error}
			</div>
		);
	}

	return (
		<div
			className="mermaid-diagram my-6 overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--muted)]/20 p-4 sm:p-6 [&_svg]:max-w-full [&_svg]:h-auto"
			// Mermaid returns a generated SVG, with strict security mode enabled above.
			// biome-ignore lint/security/noDangerouslySetInnerHtml: generated by Mermaid
			dangerouslySetInnerHTML={{ __html: svg }}
		/>
	);
}
