"use client";

import mermaid from "mermaid";
import { useEffect, useId, useState } from "react";

interface MermaidDiagramProps {
	chart: string;
}

export function MermaidDiagram({ chart }: MermaidDiagramProps) {
	const reactId = useId();
	const [svg, setSvg] = useState("");
	const [error, setError] = useState("");

	useEffect(() => {
		let active = true;
		const id = `mermaid-${reactId.replace(/[^a-zA-Z0-9]/g, "")}`;

		mermaid.initialize({
			startOnLoad: false,
			securityLevel: "strict",
			theme: document.documentElement.classList.contains("dark")
				? "dark"
				: "default",
			flowchart: { htmlLabels: false, useMaxWidth: true },
		});

		mermaid
			.render(id, chart)
			.then(({ svg: renderedSvg }) => {
				if (active) setSvg(renderedSvg);
			})
			.catch((reason: unknown) => {
				if (active) {
					setError(reason instanceof Error ? reason.message : "Invalid diagram");
				}
			});

		return () => {
			active = false;
		};
	}, [chart, reactId]);

	if (error) {
		return (
			<div className="my-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4 font-mono text-sm text-red-500">
				Diagram error: {error}
			</div>
		);
	}

	return (
		<div
			className="mermaid-diagram my-6 overflow-x-auto rounded-xl border border-[var(--border)] bg-[var(--muted)]/20 p-4 sm:p-6"
			// Mermaid returns a generated SVG, with strict security mode enabled above.
			// biome-ignore lint/security/noDangerouslySetInnerHtml: generated by Mermaid
			dangerouslySetInnerHTML={{ __html: svg }}
		/>
	);
}
